apiVersion: v1
kind: Pod
metadata:
  name: my-first-nginx
  namespace: default
  labels:
    app: web-test
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    ports:
    - containerPort: 80
